### ISSUE TITLE
zip files for images are corrupted and possible wrong URL

### ISSUE THREAD

**Issue by minghao-wu** [KenrickLance/BalitaNLP-Dataset#1]
Hi,

I downloaded images zip files via the provided URLs, but all the zip files are corrupted with the error message as follows:
```
Archive:  BalitaNLP-images_4.zip
warning [BalitaNLP-images_4.zip]:  4586415792 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [BalitaNLP-images_4.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```
Additionally, the URL link for part 3 seems to be wrong, as it's identical to the URL link for part 2.

**Comment by KenrickLance** [comment]
Thanks for pointing these out! I'll fix these soon in the next few days.

**Comment by KenrickLance** [comment]
Fixed the link. The zip files are working for me. Tested downloading them and unzipping with WinRAR
